# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/tsocial/TrustVisionPodspec.git'

target 'TrustVisionSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrustVisionSample
  pod 'TrustVisionFramework'

  target 'TrustVisionSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrustVisionSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
